openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: some api
  termsOfService: https://www.example.com/tos
  contact:
    email: contact@email.com
    name: My Team
    url: https://www.example.com/contact
  license:
    name: My License
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server
paths:
  /users:
    summary: base user level operations
    description: fetch all users, create new users
    get:
      summary: fetch all users
      description: return all users from server
      operationId: fetchUsers
      responses:
        '200':
          description: successful fetch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - Users
components:
  schemas:
    FullUser:
      type: object
      properties:
        id: 
          type: string
          example: qwerty
        username:
          type: string
          example: bear
        score:
          type: integer
          example: 55
        active:
          type: boolean
          example: true
    
