openapi: 3.0.1
info:
  title: My API 4 pm
  version: '1.0'
  description: my api to the data that...
  termsOfService: https://www.example.com/tos
  contact:
    email: bear@example.com
    name: Support Team
    url: https://www.example.com/contact
  license:
    name: License Here
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: mock server on github
paths:
  /users:
    summary: user operations
    description: create and fetch users
    get:
      summary: fetch users
      description: returns users from server
      operationId: fetchUsers
      responses:
        default:
          description: Default error sample response
      tags:
        - Users
