openapi: 3.0.1
info:
  title: MySEBAPI
  version: 1.0.2
  description: this great api from SEB
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: my fake api server local
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake api server on github
paths:
  /users:
    summary: user level operations
    description: fetch users, create new users
    get:
      summary: fetch users from server
      description: returns users from server
      operationId: fetchUsers
      responses:
        '200':
          description: successful response of user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create a new user
      description: store a user on the server
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostNewUser'
      responses:
        '201':
          description: successful response of user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - users
components:
  schemas:
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: bear2133
        score:
          type: integer
          example: 66
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - $ref: '#/components/schemas/PostNewUser'
        - type: object
          properties:
            id:
              type: string
              example: 1234asdf
