openapi: 3.0.1
info:
  title: My API 4 pm
  version: '1.0'
  description: my api to the data that...
  termsOfService: https://www.example.com/tos
  contact:
    email: bear@example.com
    name: Support Team
    url: https://www.example.com/contact
  license:
    name: License Here
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: local mock server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: mock server on github
paths:
  /users:
    summary: user operations
    description: create and fetch users
    get:
      summary: fetch users
      description: returns users from server
      operationId: fetchUsers
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: server message
                  code:
                    type: integer
                    example: 980
      tags:
        - Users
    post:
      summary: create new user
      description: store user on server
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostNewUser'
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - Users
components:
  schemas:
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: bear
        score:
          type: integer
          example: 55
        active:
          type: boolean
          example: true
    FullUser:
      type: object
      properties:
        id:
          type: string
          example: 1234abc
        username:
          type: string
          example: bear
        score:
          type: integer
          example: 55
        active:
          type: boolean
          example: true
