openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: An API that...
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000/
    variables: {}
    description: local fake server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: github mock server
paths:
  /users:
    summary: user operations
    description: GET and POST on Users
    get:
      summary: user operations
      description: fetch users
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - Users
    post:
      summary: create a new user
      description: store new user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - Users
components:
  responses:
    UserRespBody:
      description: fetched users
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
  requestBodies:
    UserPostBody:
      description: user content for POST
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostNewUser'
  schemas:
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: test2
        score:
          type: integer
          example: 55
        active:
          type: boolean
          example: true 
    FullUser:
      allOf:
        - $ref: '#/components/schemas/PostNewUser'
        - type: object
          properties:
            id:
              type: string
              example: 1234abc
