openapi: 3.0.1
info:
  title: MyAPISEBPM1
  version: '1.0'
  description: my api for data using...
  termsOfService: https://www.example.com/tos
  contact:
    email: test@email.com
    name: Support Team
    url: https://www.example.com/support
  license:
    name: My License
    url: https://www.example.com/lic
servers:
  - url: https://my-json-server.typicode.com/typicode/demo
    variables: {}
    description: my demo server
