openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: some great api
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/contact
servers:
  - url: http://localhost:3000
    variables: {}
    description: my fake local server api
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server api
  - url: '{scheme}://www.example.com:{port}/{version}'
    variables:
      scheme:
        default: https
        enum:
          - https
          - http
        description: ssl or not
      port:
        default: '8080'
        enum:
          - '8080'
          - '8081'
          - '8082'
        description: port numbers for dev, test and production
      version:
        default: v3
        enum:
          - v3
          - v2
          - v1
        description: version of api
    description: example with variables
paths:
  /users:
    summary: base user level operations
    description: fetch (GET) all users, create (POST) a new user
    get:
      summary: fetch all users
      description: return all users from the server
      operationId: fetchUsers
      responses:
        2XX:
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - Users
    post:
      summary: create a new user
      description: store user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - Users
components:
  responses:
    UserArrayResponseBody:
      description: array of users
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
    UserRespBody:
      description: successful creation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
  requestBodies:
    UserPostBody:
      required: true
      description: new user POST
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewPostBody'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    NewPostBody:
      type: object
      properties:
        username:
          type: string
          example: bear
        score:
          type: integer
          example: 99
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - type: object
          properties:
            id:
              type: string
              example: qwerty
        - $ref: '#/components/schemas/NewPostBody'
