openapi: 3.0.1
info:
  title: My SEB API
  version: '1.0'
  description: the most useful api...
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: Support Team
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: local fake server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server
paths:
  /users:
    summary: fetch all users, create a new user
    description: user level operations
    get:
      summary: fetch all users
      description: returns users from server
      operationId: fetchUsers
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create new user
      description: store user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
components:
  responses:
    UserRespBody:
      description: success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
  requestBodies:
    UserPostBody:
      description: new user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostNewUser'
  schemas:
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: bear23432
        score:
          type: integer
          example: 67
        active:
          type: boolean
          example: false
    FullUser:
      allOf:
      - $ref: '#/components/schemas/PostNewUser'
      - type: object
        properties:
          id:
            type: string
            example: 1234asdf
