openapi: 3.0.1
info:
  title: SEB 1
  version: '1.0'
  description: my api for fetching and storing data
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: local server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake server at github
paths:
  /users:
    summary: base level for users
    description: fetch all users, create new users
    get:
      summary: fetch all users
      description: returns all users from server
      operationId: fetchUsers
      responses:
        2XX:
          $ref: '#/components/responses/UserArrayResp'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create a new user
      description: store a user on the server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        201:
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
components:
  responses:
    UserArrayResp:
      description: multiple users
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
    UserRespBody:
      description: successful create
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
  requestBodies:
    UserPostBody:
      description: body of new user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewUser'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    NewUser:
      type: object
      properties:
        username:
          type: string
          example: bearuser
        score:
          type: integer
          example: 56
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - type: object
          properties:
            id:
              type: string
              example: 1234abc
        - $ref: '#/components/schemas/NewUser'
