openapi: 3.0.1
info:
  title: SEB 1
  version: '1.0'
  description: my api for fetching and storing data
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake server at github
paths:
  /users:
    summary: base level for users
    description: fetch all users, create new users
    get:
      summary: fetch all users
      description: returns all users from server
      operationId: fetchUsers
      responses:
        '2XX':
          description: successful fetch
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 1234abc
                  username:
                    type: string
                    example: bearuser
                  score:
                    type: integer
                    example: 56
                  active:
                    type: boolean
                    example: true
        default:
          description: Default error sample response
      tags:
        - users
