openapi: 3.0.1
info:
  title: My SEB API
  version: '1.0'
  description: an api to do some stuff...
  termsOfService: https://www.example.com
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: my local fake server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server
paths:
  /users:
    summary: users path level operations
    description: returns users from server, create a user
    get:
      summary: fetch users from server
      description: returns users from online
      operationId: fetchUsers
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create a new user
      description: stores user on server
      operationId: createUser
      requestBody:
        description: request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: bearc
                score:
                  type: integer
                  example: 234
                action:
                  type: boolean
                  example: true
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - users
components:
  schemas:
    FullUser:
      type: object
      properties:
        id:
          type: string
          example: 1234abc
        username:
          type: string
          example: bearc
        score:
          type: integer
          example: 234
        action:
          type: boolean
          example: true
