openapi: 3.0.1
info:
  title: My SEB API
  version: '1.0'
  description: the most useful api...
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: Support Team
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server
paths:
  /users:
    summary: fetch all users, create a new user
    description: user level operations
    get:
      summary: fetch all users
      description: returns users from server
      operationId: fetchUsers
      responses:
        default:
          description: Default error sample response
      tags:
        - users
