openapi: 3.0.1
info:
  title: Cohort 6 API
  version: '1.0'
  description: My api that does stuff with data
  termsOfService: http://www.example.com/tos
  contact:
    email: bear@brainwashinc.com
    name: Bear Cahill
    url: http://www.example.com/contact
  license:
    name: License
    url: http://www.example.com/license
servers:
  - url: http://localhost:3000/
    variables: {}
    description: my local server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my github account json
  - url: https://my-json-server.typicode.com/typicode/demo
    variables: {}
    description: github demo api server
paths:
  /posts:
    summary: posts level operations
    description: create new post, fetch all posts
    get:
      summary: fetch all posts
      description: returns all posts from server
      operationId: fetchPosts
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                sample:
                  value:
                    - id: 1
                      title: Post 1
                    - id: 2
                      title: Post 2
                    - id: 3
                      title: Post 3
      tags:
        - posts
    post:
      summary: add new server item
      description: store new post on server
      operationId: storePost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                  example: "bear"
                title:
                  type: string
                  example: "my post"
      responses:
        '2XX':
          description: successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 4
                  author:
                    type: string
                    example: "bear"
                  title:
                    type: string
                    example: "my post"
        default:
          description: Default error sample response
      tags:
        - posts
