openapi: 3.0.1
info:
  title: Cohort 6 API
  version: '1.0'
  description: My api that does stuff with data
  termsOfService: http://www.example.com/tos
  contact:
    email: bear@brainwashinc.com
    name: Bear Cahill
    url: http://www.example.com/contact
  license:
    name: License
    url: http://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my github account json
  - url: https://my-json-server.typicode.com/typicode/demo
    variables: {}
    description: github demo api server
