openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: api that serves...
  termsOfService: https://www.example.com
  contact:
    email: contact@example.com
    name: Support
    url: https://www.example.com/support
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: mock server at github
paths:
  /users:
    summary: create new users, fetch users
    description: user based operations
    get:
      summary: fetch users
      description: returns users from server
      operationId: fetchUsers
      responses:
        default:
          description: Default error sample response
      tags:
        - Users
