openapi: 3.0.1
info:
  title: My SEB API
  version: '1.0'
  description: the most useful api...
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: Support Team
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: my local fake server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server
  - url: https://www.example.com:{port}/{version}
    variables:
      port:
        default: '3000'
        enum:
          - '3000'
          - '3001'
        description: '3000: test, 3001: prod'
      version:
        default: v2
        enum:
          - v2
          - v1
        description: versions
    description: server variables
paths:
  /users:
    summary: fetch all users, create a new user
    description: user level operations
    get:
      summary: fetch all users
      description: returns users from server
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create a new user
      description: store user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
  /users/{userId}:
    summary: user level operations
    description: fetch, update, delete user
    parameters:
      - $ref: '#/components/parameters/UserId'
    get:
      summary: fetch a user
      description: returns a user from the server
      operationId: fetchUser
      responses:
        '200':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
    delete:
      summary: delete a user
      description: remove user from server
      operationId: deleteUser
      responses:
        default:
          description: Default error sample response
      tags:
        - users
    patch:
      summary: update user
      description: update values on server
      operationId: updateUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '200':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
components:
  parameters:
    UserId:
      name: userId
      in: path
      required: true
      description: user id
      schema:
        type: string
        example: 123abc
  requestBodies:
    UserPostBody:
      description: new user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostNewUser'
  responses:
    UserArrayResponseBody:
      description: array of users
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
    UserRespBody:
      description: success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: bear23432
        score:
          type: integer
          example: 67
        active:
          type: boolean
          example: false
    FullUser:
      allOf:
        - $ref: '#/components/schemas/PostNewUser'
        - type: object
          properties:
            id:
              type: string
              example: 1234asdf
