openapi: 3.0.1
info:
  title: My API SEB
  version: '1.0'
  description: deals with data from server
  termsOfService: https://www.example.com
  contact:
    email: b@bw1.us
    name: Bear
    url: https://www.example.com
  license:
    name: SEB License
    url: https://www.example.com/lic
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: Blog posts server
paths:
  /posts:
    get:
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Sample of Posts:
                  value: |-
                    [
                      {
                        "id": 1,
                        "title": "Post 1"
                      },
                      {
                        "id": 2,
                        "title": "Post 2"
                      },
                      {
                        "id": 3,
                        "title": "Post 3"
                      }
                    ]
      tags:
        - posts
