openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: this api that deals with...
  termsOfService: https://www.example.com/tos
  contact:
    email: team@example.com
    name: Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
