openapi: 3.0.1
info:
  title: My SEB API
  version: '1.0'
  description: some api that does stuff...
  termsOfService: https://www.example.com
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/support
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server
