openapi: 3.0.1
info:
  title: MySEBAPI
  version: 1.0.1
  description: My SEB api for...
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: API Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000/
    variables: {}
    description: My fake local server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: My fake github server
  - url: https://www.example.com:{port}/api
    variables:
      port:
        default: '3000'
        enum:
          - '3000'
          - '3003'
          - '3002'
        description: 3000 is test, 3003 is dev, 3002 is prod
    description: test server
paths:
  /users:
    summary: user level operations
    description: fetch all users, create new user
    get:
      summary: fetch all users
      description: returns all users from server
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserArrayResp'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create a new user
      description: store a user on the server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/PostBody'
      responses:
        '201':
          $ref: '#/components/responses/RespBody'
        default:
          description: Default error sample response
      tags:
        - users
    put:
      summary: update a new user
      description: update a user on the server
      operationId: replaceUser
      requestBody:
        $ref: '#/components/requestBodies/PostBody'
      responses:
        '201':
          $ref: '#/components/responses/RespBody'
        default:
          description: Default error sample response
      tags:
        - users
  /users/{userId}:
    summary: user based operations
    description: update and delete user
    parameters:
      - $ref: '#/components/parameters/UserId'
    get:
      summary: fetch a user
      description: returns a user from the server
      operationId: fetchUser
      responses:
        '200':
          $ref: '#/components/responses/RespBody'
        default:
          description: Default error sample response
      tags:
        - users
    delete:
      summary: delete a user
      description: delete a user from the server
      operationId: deleteUser
      responses:
        default:
          description: Default error sample response
      tags:
        - users
    patch:
      summary: update a new user
      description: update a user on the server
      operationId: updateUser
      requestBody:
        $ref: '#/components/requestBodies/PostBody'
      responses:
        '200':
          $ref: '#/components/responses/RespBody'
        default:
          description: Default error sample response
      tags:
        - users
components:
  parameters:
    UserId:
      name: userId
      in: path
      required: true
      description: the user id
      schema:
        type: string
        example: bear1234    
  responses:
    UserArrayResp:
      description: success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
    RespBody:
      description: success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
  requestBodies:
    PostBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewUser'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    NewUser:
      type: object
      properties:
        username:
          type: string
          example: bear123
        score:
          type: integer
          example: 56
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - $ref: '#/components/schemas/NewUser'
        - type: object
          properties:
            id:
              type: string
              example: 1234dsaf
