openapi: 3.0.1
info:
  title: MySEBAPI
  version: 1.0.2
  description: this great api from SEB
  termsOfService: https://www.example.com/tos
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: my fake api server local
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake api server on github
  - url: https://my-json-server.typicode.com/{gitaccount}/{reponame}
    variables:
      gitaccount:
        default: bearc0025
        enum:
          - bearc0025
          - abc1234
          - 1234asdf
        description: 'bearc0025: dev, abc1234: test, 1234asdf: production'
      reponame:
        default: api
        enum:
          - api
          - sebapi
        description: desc here
    description: online fake server
paths:
  /users:
    summary: user level operations
    description: fetch users, create new users
    get:
      summary: fetch users from server
      description: returns users from server
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create a new user
      description: store a user on the server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
  /users/{userId}:
    summary: indiv user operations
    description: fetch, update, delete user
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          example: qwerty
    get:
      summary: fetch a user
      description: return a user from the server
      operationId: fetchUser
      responses:
        '200':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
components:
  responses:
    UserArrayResponseBody:
      description: array of users
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
    UserRespBody:
      description: successful response of user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
  requestBodies:
    UserPostBody:
      description: post for new user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostNewUser'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: bear2133
        score:
          type: integer
          example: 66
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - $ref: '#/components/schemas/PostNewUser'
        - type: object
          properties:
            id:
              type: string
              example: 1234asdf
