openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: api that serves...
  termsOfService: https://www.example.com
  contact:
    email: contact@example.com
    name: Support
    url: https://www.example.com/support
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http:localhost:3000
    variables: {}
    description: local fake server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: mock server at github
paths:
  /users:
    summary: create new users, fetch users
    description: user based operations
    get:
      summary: fetch users
      description: returns users from server
      operationId: fetchUsers
      responses:
        '200':
          description: users returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - Users
    post:
      summary: create new user
      description: store user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          description: users returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - Users
components:
  requestBodies:
    UserPostBody:
      description: body of user in POST
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostNewUser'
  schemas:
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: bear
        score:
          type: integer
          example: 55
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - $ref: '#/components/schemas/PostNewUser'
        - type: object
          properties:
            id:
              type: string
              example: 1234abc
