openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: this api that deals with...
  termsOfService: https://www.example.com/tos
  contact:
    email: team@example.com
    name: Support
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server
paths:
  /users:
    summary: fetch and create users
    description: returns users, stores users
    get:
      summary: fetch users from server
      description: returns users
      operationId: fetchUsers
      responses:
        default:
          description: Default error sample response
      tags:
        - Users
