openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: some great api
  contact:
    email: support@example.com
    name: Support
    url: https://www.example.com/contact
servers:
  - url: http://localhost:3000
    variables: {}
    description: my fake local server api
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake github server api
paths:
  /users:
    summary: base user level operations
    description: fetch (GET) all users, create (POST) a new user
    get:
      summary: fetch all users
      description: return all users from the server
      operationId: fetchUsers
      responses:
        '2XX':
          description: successful fetch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullUser'
        default:
          description: Default error sample response
      tags:
        - Users
components:
  schemas:
    FullUser:
      type: object
      properties:
        id:
          type: string
          example: qwerty
        username:
          type: string
          example: bear
        score:
          type: integer
          example: 99
        active:
          type: boolean
          example: true
    
